
import { Metadata } from "next";
import NewsAndBlogsWrapper from "./NewsAndBlogLayoutWrapper";

export const metadata: Metadata = {
    title: "News | Blogs",
    description: "Generated by create next app",
};


export default function NewsAndBlogLayout({
    children,
}: {
    children: React.ReactNode;
}) {



    return (
        <div className="flex  overflow-hidden">
            <div className="flex-1 flex flex-col overflow-hidden">
                <main className="flex-1">
                    <NewsAndBlogsWrapper> {children} </NewsAndBlogsWrapper>
                </main>
            </div>
        </div>
    );
}
