
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "NFTs",
    description: "Generated by create next app",
};


export default function MainLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    return (
        <div className="flex overflow-hidden">
            <div className="flex-1 flex flex-col overflow-hidden">
                {/* Conditional Rendering */}
                <main className="flex-1 overflow-y-auto">
                    {children}
                </main>
            </div>
        </div>
    );
}
