import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./providers";
import { Toaster } from "sonner";
import PublicLayoutClient from "./PublicLayoutClient";
import { ThemeProvider } from "@/providers/ThemeProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "The Coin Cartel",
  description: "Generated by create next app",
  other: {
    "the-coin-cartel": "24cda809b6ff"
  }
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${inter.variable} bg-background transition-colors`}
      >
        <ThemeProvider>
          <ReduxProvider>
            <PublicLayoutClient>{children}</PublicLayoutClient>
            <Toaster />
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
